name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Test and generate coverage report
        run: go test -v -race -failfast -parallel 4 -cpu 4 -coverprofile main.cover.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          name: codecov-umbrella
          files: ./main.cover.out
          flags: unittests
          fail_ci_if_error: true
          verbose: true
